name: Build WiX Toolset v6

on:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: windows-2022
    env:
      RepoOrg: wixtoolset
      SignBuild: false
      WixOfficialBuild: false
    steps:
      - name: Checkout iswix code
        uses: actions/checkout@v4
        with:
          path: wix-ci
          fetch-depth: 0
      - name: Checkout wix code
        uses: actions/checkout@v4
        with:
          repository: wixtoolset/wix

      - name: Examine
        shell: cmd
        run: dir
        
