name: Build WiX Toolset v6

on:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: windows-2022
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
